version: "3.2"
services:
  estagio-fatec-push:
    container_name: estagio-fatec-push
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/usr/src/app
    networks:
      - infra-estagio-network
    env_file:
      - .env
    dns:
      - 8.8.8.8
networks:
  infra-estagio-network:
    external: true